name: mssql-dev
services:
  mssql-dev:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql-dev
    restart: unless-stopped
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${ROOT_PASSWORD}"
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: "true"   # required for CDC capture/cleanup jobs
    volumes:
      - data:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P \"$${MSSQL_SA_PASSWORD}\" -Q \"SELECT 1;\" || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 30

  mssql-dev-setup:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-dev-setup
    depends_on:
      mssql-dev:
        condition: service_healthy
    environment:
      MSSQL_SA_PASSWORD: "${ROOT_PASSWORD}"
      DATABASE: "${DATABASE}"
      DB_USER: "${DB_USER}"
      DB_USER_PASSWORD: "${DB_USER_PASSWORD}"
    volumes:
      - ./init.sql:/scripts/init.sql:ro
    entrypoint: ["/bin/bash", "-lc", "/opt/mssql-tools18/bin/sqlcmd -C -S mssql-dev,1433 -U sa -P \"$${MSSQL_SA_PASSWORD}\" -i /scripts/init.sql && echo 'âœ… MSSQL init done'"]

volumes:
  data:
